server:
  port: 9000
spring:
  application:
    name: tajkun-ad-gateway
eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/
zuul:
  prefix: /api
  routes:
    delivery:
      path: /delivery/**
      serviceId: tajkun-ad-delivery
      strip-prefix: false  # 不过滤前缀delivery
    search:
      path: /search/**
      serviceId: tajkun-ad-search
      strip-prefix: false
    datadump:
      path: /datadump/**
      serviceId: tajkun-ad-datadump
      strip-prefix: false