server:
  port: 7002
  servlet:
    context-path: /binlogmq

spring:
  application:
    name: tajkun-ad-binlogmq
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tajkun_ad?autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
  kafka:
    bootstrap-servers: 39.97.102.53:9092
    listener:
      concurrency: 4

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

adconfig:
  mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password: root
    binlogName:
    position: -1

  kafka:
    topic: tajkun-ad-binlog-mysql-rowData