server:
  port: 7000
  servlet:
    context-path: /delivery   # 相当于请求controller的前缀

spring:
  application:
    name: tajkun-ad-delivery
  jpa:
    show-sql: true  # 打印sql语句
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false  # 懒加载时要设置为false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tajkun_ad?autoReconnect=true
    username: root
    password: root
    tomcat:
      max-active: 4  # 数据库连接池最大连接数
      min-idle: 2    # 最小连接数
      initial-size: 2 #默认连接数
eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/
